version: '3.1'

services:

  jadio-mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: ****
    volumes:
      - ${MONGO_ROOT}/db:/data/mongo/db
      - ${MONGO_ROOT}/configdb:/data/mongo/configdb

  jadio-httpd:
    image: httpd:2.4
    restart: always
    ports:
      - ${HTTPD_PORT}:80
    volumes:
      - ${MEDIA_ROOT}:/usr/local/apache2/htdocs/media:ro
      - ${RSS_ROOT}:/usr/local/apache2/htdocs/rss:ro

  jadio-cron:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    shm_size: 2g
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - HTTPD_HOST=${HTTPD_HOST}
    volumes:
      - ${CONFIG_ROOT}:/data/config
      - ${MEDIA_ROOT}:/data/media
      - ${RSS_ROOT}:/data/rss
