version: '3.1'

services:

  jadio-mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: ****
    volumes:
      - ${SVR_ROOT}/mongo/data/db:/data/db
      - ${SVR_ROOT}/mongo/data/configdb:/data/configdb

  jadio-recorder:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    shm_size: 2g
    environment:
      - MONGO_HOST=${MONGO_HOST}
    volumes:
      - ${SVR_ROOT}/jadio-recorder:/data/jadio-recorder
      - ${MEDIA_ROOT}:/data/media
