version: '3.1'

services:

  mongo:
    # use mongo:4.4.6 to avoid following error:
    # MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
    # https://stackoverflow.com/questions/70818543/mongo-db-deployment-not-working-in-kubernetes-because-processor-doesnt-have-avx
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: ****
    volumes:
      - ${SVR_ROOT}/mongo/data/db:/data/db
      - ${SVR_ROOT}/mongo/data/configdb:/data/configdb

  jadio-recorder:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    shm_size: 2g
    volumes:
      - ${SVR_ROOT}/jadio-recorder:/data/jadio-recorder
      - ${MEDIA_ROOT}:/data/media
